import PDFDocument from 'pdfkit';

export const reportService = {
  /**
   * Generate a PDF report stream for an analyzed document
   */
  generatePdfReport: (doc, summary, clauses) => {
    return new Promise((resolve, reject) => {
      try {
        const pdf = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers = [];

        pdf.on('data', buffer => buffers.push(buffer));
        pdf.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });
        pdf.on('error', err => reject(err));

        // Header
        pdf.fillColor('#1E293B').fontSize(22).font('Helvetica-Bold').text('Terms & Conditions Risk Analysis', 40, 40);
        pdf.fontSize(10).font('Helvetica').fillColor('#64748B').text(`Generated on ${new Date().toLocaleDateString()} | AI Terms & Conditions Explainer`, 40, 68);

        pdf.moveTo(40, 85).lineTo(555, 85).strokeColor('#CBD5E1').lineWidth(1).stroke();

        // Document Info Box
        pdf.rect(40, 95, 515, 60).fillAndStroke('#F8FAFC', '#E2E8F0');
        pdf.fontSize(11).font('Helvetica-Bold').fillColor('#0F172A').text('Document:', 55, 108);
        pdf.font('Helvetica').fillColor('#334155').text(doc.file_name || 'Terms Agreement', 125, 108);

        pdf.font('Helvetica-Bold').fillColor('#0F172A').text('Overall Risk:', 55, 128);
        const riskColor = doc.risk_level === 'High' ? '#DC2626' : doc.risk_level === 'Medium' ? '#D97706' : '#16A34A';
        pdf.font('Helvetica-Bold').fillColor(riskColor).text(`${doc.risk_level || 'Moderate'} Risk (${doc.risk_score || 50}/100)`, 135, 128);

        let y = 175;

        // Executive Summary
        pdf.fontSize(14).font('Helvetica-Bold').fillColor('#1E293B').text('Executive Summary (Plain English)', 40, y);
        y += 20;

        pdf.fontSize(10).font('Helvetica').fillColor('#334155').text(summary?.summary_text || 'No summary available.', 40, y, {
          width: 515,
          align: 'left',
          lineGap: 3
        });
        y = pdf.y + 15;

        // Key Takeaways
        if (summary?.key_takeaways && summary.key_takeaways.length > 0) {
          if (y > 700) { pdf.addPage(); y = 40; }
          pdf.fontSize(12).font('Helvetica-Bold').fillColor('#1E293B').text('Key Takeaways:', 40, y);
          y += 18;
          summary.key_takeaways.forEach((point) => {
            if (y > 740) { pdf.addPage(); y = 40; }
            pdf.fontSize(10).font('Helvetica').fillColor('#334155').text(`•  ${point}`, 50, y, { width: 505 });
            y = pdf.y + 6;
          });
          y += 10;
        }

        // Flagged Risky Clauses
        if (y > 680) { pdf.addPage(); y = 40; }
        pdf.fontSize(14).font('Helvetica-Bold').fillColor('#1E293B').text(`Flagged Concerning Clauses (${clauses.length})`, 40, y);
        y += 22;

        clauses.forEach((c, idx) => {
          if (y > 650) {
            pdf.addPage();
            y = 40;
          }

          const cardColor = c.risk_level === 'High' ? '#FEF2F2' : c.risk_level === 'Medium' ? '#FFFBEB' : '#F0FDF4';
          const borderColor = c.risk_level === 'High' ? '#FCA5A5' : c.risk_level === 'Medium' ? '#FCD34D' : '#86EFAC';
          const badgeBg = c.risk_level === 'High' ? '#DC2626' : c.risk_level === 'Medium' ? '#D97706' : '#16A34A';

          // Card header
          pdf.fontSize(11).font('Helvetica-Bold').fillColor('#0F172A').text(`${idx + 1}. ${c.category || 'General Risk'}`, 45, y);
          pdf.fontSize(9).font('Helvetica-Bold').fillColor(badgeBg).text(`[ ${c.risk_level?.toUpperCase() || 'MODERATE'} RISK ]`, 420, y, { align: 'right', width: 130 });
          y += 16;

          // Original Clause Quote
          pdf.fontSize(9).font('Helvetica-Oblique').fillColor('#475569').text(`"${c.clause_text}"`, 55, y, { width: 495 });
          y = pdf.y + 8;

          // Explanation
          pdf.fontSize(10).font('Helvetica-Bold').fillColor('#1E293B').text('Why this matters:', 55, y);
          y += 13;
          pdf.fontSize(9).font('Helvetica').fillColor('#334155').text(c.explanation || 'Requires user attention.', 55, y, { width: 495 });
          y = pdf.y + 8;

          // Recommendation
          if (c.recommendation) {
            pdf.fontSize(9).font('Helvetica-Bold').fillColor('#2563EB').text('Tip / Recommendation: ', 55, y, { continued: true });
            pdf.font('Helvetica').fillColor('#334155').text(c.recommendation, { width: 495 });
            y = pdf.y + 8;
          }

          pdf.moveTo(45, y).lineTo(550, y).strokeColor('#E2E8F0').lineWidth(0.5).stroke();
          y += 12;
        });

        // Footer Disclaimer
        if (y > 750) { pdf.addPage(); y = 750; }
        pdf.moveTo(40, 780).lineTo(555, 780).strokeColor('#E2E8F0').stroke();
        pdf.fontSize(8).font('Helvetica').fillColor('#94A3B8').text(
          'Disclaimer: This report is generated by an automated AI tool for informational purposes only and does not constitute formal legal counsel.',
          40, 788, { align: 'center', width: 515 }
        );

        pdf.end();
      } catch (e) {
        reject(e);
      }
    });
  }
};
